/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Mesh001: THREE.Mesh;
    Mesh001_1: THREE.Mesh;
    Mesh001_2: THREE.Mesh;
    Mesh001_3: THREE.Mesh;
    Mesh001_4: THREE.Mesh;
    Mesh001_5: THREE.Mesh;
    Mesh001_6: THREE.Mesh;
    Mesh003: THREE.Mesh;
    Mesh003_1: THREE.Mesh;
    Mesh003_2: THREE.Mesh;
    Mesh003_3: THREE.Mesh;
    Mesh003_4: THREE.Mesh;
    Mesh003_5: THREE.Mesh;
    Mesh003_6: THREE.Mesh;
    tank_4001: THREE.Mesh;
    floor_4001: THREE.Mesh;
    pipes_4001: THREE.Mesh;
    roof_4001: THREE.Mesh;
    ["75_water_4001"]: THREE.Mesh;
    ladder_4001: THREE.Mesh;
    ["100_water_3"]: THREE.Mesh;
    ["25_water_3"]: THREE.Mesh;
    ["75_water_3"]: THREE.Mesh;
    ["50_water_3"]: THREE.Mesh;
    tank_3: THREE.Mesh;
    Mesh059: THREE.Mesh;
    Mesh059_1: THREE.Mesh;
    Mesh059_2: THREE.Mesh;
    pipes_4: THREE.Mesh;
    roof_4: THREE.Mesh;
    tank_4: THREE.Mesh;
    ["100_water_4"]: THREE.Mesh;
    ["25_water_4"]: THREE.Mesh;
    ["50_water_4"]: THREE.Mesh;
    ["75_water_4"]: THREE.Mesh;
    floor_4: THREE.Mesh;
    ladder_4: THREE.Mesh;
    ["100_water_2"]: THREE.Mesh;
    ["50_water_2"]: THREE.Mesh;
    floor_2: THREE.Mesh;
    pipes_2: THREE.Mesh;
    roof_2: THREE.Mesh;
    tank_2: THREE.Mesh;
    ["25_water_2"]: THREE.Mesh;
    ["75_water_2"]: THREE.Mesh;
    ladder_2: THREE.Mesh;
    ["100_water"]: THREE.Mesh;
    ["50_water"]: THREE.Mesh;
    floor: THREE.Mesh;
    pipes: THREE.Mesh;
    roof: THREE.Mesh;
    tank: THREE.Mesh;
    ["25_water"]: THREE.Mesh;
    ["75_water"]: THREE.Mesh;
    ladder: THREE.Mesh;
    BATTERY_BOX_2: THREE.Mesh;
    BATTERY_BOX_instance_4: THREE.Mesh;
    BATTERY_BOX_instance_5: THREE.Mesh;
    BATTERY_BOX_instance_6: THREE.Mesh;
    BATTERY_BOX: THREE.Mesh;
    BATTERY_BOX_instance: THREE.Mesh;
    BATTERY_BOX_instance_2: THREE.Mesh;
    BATTERY_BOX_instance_3: THREE.Mesh;
    Mesh076: THREE.Mesh;
    Mesh076_1: THREE.Mesh;
    Mesh076_2: THREE.Mesh;
    Mesh076_3: THREE.Mesh;
    Mesh076_4: THREE.Mesh;
    Mesh076_5: THREE.Mesh;
    Mesh076_6: THREE.Mesh;
    Mesh076_7: THREE.Mesh;
    Mesh076_8: THREE.Mesh;
    Mesh076_9: THREE.Mesh;
    Mesh076_10: THREE.Mesh;
    Mesh076_11: THREE.Mesh;
    Mesh076_12: THREE.Mesh;
    Mesh076_13: THREE.Mesh;
    Mesh076_14: THREE.Mesh;
    Mesh076_15: THREE.Mesh;
    Mesh076_16: THREE.Mesh;
    Mesh076_17: THREE.Mesh;
    Mesh076_18: THREE.Mesh;
    Mesh076_19: THREE.Mesh;
    Mesh076_20: THREE.Mesh;
    Mesh076_21: THREE.Mesh;
    Mesh076_22: THREE.Mesh;
    Mesh076_23: THREE.Mesh;
    Mesh076_24: THREE.Mesh;
    Mesh076_25: THREE.Mesh;
    Mesh076_26: THREE.Mesh;
    Mesh076_27: THREE.Mesh;
    Mesh076_28: THREE.Mesh;
    Mesh076_29: THREE.Mesh;
    Mesh076_30: THREE.Mesh;
    Mesh076_31: THREE.Mesh;
    Mesh076_32: THREE.Mesh;
    Mesh076_33: THREE.Mesh;
    Mesh076_34: THREE.Mesh;
    Mesh076_35: THREE.Mesh;
    Mesh076_36: THREE.Mesh;
    Mesh076_37: THREE.Mesh;
    Mesh076_38: THREE.Mesh;
    Mesh076_39: THREE.Mesh;
    Mesh076_40: THREE.Mesh;
    Mesh076_41: THREE.Mesh;
    Mesh076_42: THREE.Mesh;
    Mesh076_43: THREE.Mesh;
    Mesh076_44: THREE.Mesh;
    Mesh087: THREE.Mesh;
    Mesh087_1: THREE.Mesh;
    Mesh033: THREE.Mesh;
    Mesh033_1: THREE.Mesh;
    Generator_1: THREE.Mesh;
    Generator_1_1: THREE.Mesh;
    Generator_1_2: THREE.Mesh;
    Generator_1_3: THREE.Mesh;
    Generator_1_4: THREE.Mesh;
    Generator_1_5: THREE.Mesh;
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Mesh_3: THREE.Mesh;
    Mesh_4: THREE.Mesh;
    Mesh_5: THREE.Mesh;
    Mesh081: THREE.Mesh;
    Mesh081_1: THREE.Mesh;
    Mesh081_2: THREE.Mesh;
    Mesh081_3: THREE.Mesh;
    Mesh081_4: THREE.Mesh;
    Mesh081_5: THREE.Mesh;
    Mesh081_6: THREE.Mesh;
    Mesh081_7: THREE.Mesh;
    Mesh081_8: THREE.Mesh;
    Mesh081_9: THREE.Mesh;
    Mesh081_10: THREE.Mesh;
    Mesh081_11: THREE.Mesh;
    Mesh081_12: THREE.Mesh;
    Mesh081_13: THREE.Mesh;
    Mesh081_14: THREE.Mesh;
    Mesh081_15: THREE.Mesh;
    Mesh081_16: THREE.Mesh;
    Mesh081_17: THREE.Mesh;
    Mesh081_18: THREE.Mesh;
    Mesh081_19: THREE.Mesh;
    Mesh081_20: THREE.Mesh;
    Mesh081_21: THREE.Mesh;
    Mesh081_22: THREE.Mesh;
    Mesh081_23: THREE.Mesh;
    Mesh081_24: THREE.Mesh;
    Mesh081_25: THREE.Mesh;
    Mesh081_26: THREE.Mesh;
    Mesh081_27: THREE.Mesh;
    Mesh081_28: THREE.Mesh;
    Mesh081_29: THREE.Mesh;
    Mesh081_30: THREE.Mesh;
    Mesh081_31: THREE.Mesh;
    Mesh081_32: THREE.Mesh;
    Mesh081_33: THREE.Mesh;
    Mesh081_34: THREE.Mesh;
    Mesh081_35: THREE.Mesh;
    Mesh081_36: THREE.Mesh;
    Mesh081_37: THREE.Mesh;
    Mesh081_38: THREE.Mesh;
    Mesh081_39: THREE.Mesh;
    Mesh081_40: THREE.Mesh;
    Mesh081_41: THREE.Mesh;
    Mesh081_42: THREE.Mesh;
    Mesh081_43: THREE.Mesh;
    Mesh081_44: THREE.Mesh;
    Mesh081_45: THREE.Mesh;
    Mesh081_46: THREE.Mesh;
    Mesh081_47: THREE.Mesh;
    Mesh081_48: THREE.Mesh;
    Mesh081_49: THREE.Mesh;
    Mesh081_50: THREE.Mesh;
    Mesh081_51: THREE.Mesh;
    Mesh081_52: THREE.Mesh;
    Mesh081_53: THREE.Mesh;
    Mesh081_54: THREE.Mesh;
    Mesh081_55: THREE.Mesh;
    Mesh081_56: THREE.Mesh;
    Mesh081_57: THREE.Mesh;
    Mesh081_58: THREE.Mesh;
    Mesh081_59: THREE.Mesh;
    Mesh002: THREE.Mesh;
    Mesh002_1: THREE.Mesh;
    Mesh002_2: THREE.Mesh;
    Mesh002_3: THREE.Mesh;
    Mesh002_4: THREE.Mesh;
    Mesh002_5: THREE.Mesh;
    Generator_1001: THREE.Mesh;
    Generator_1001_1: THREE.Mesh;
    Generator_1001_2: THREE.Mesh;
    Generator_1001_3: THREE.Mesh;
    Generator_1001_4: THREE.Mesh;
    Generator_1001_5: THREE.Mesh;
  };
  materials: {
    ["Battery Box.001"]: THREE.MeshStandardMaterial;
    ["Power Box.004"]: THREE.MeshStandardMaterial;
    ["Battery Box.007"]: THREE.MeshStandardMaterial;
    ["Concrete.001"]: THREE.MeshStandardMaterial;
    ["Color.001"]: THREE.MeshStandardMaterial;
    ["Substation Box.001"]: THREE.MeshStandardMaterial;
    ["Switch Box.001"]: THREE.MeshStandardMaterial;
    ["Battery Box.008"]: THREE.MeshStandardMaterial;
    ["Power Box.005"]: THREE.MeshStandardMaterial;
    ["Battery Box.009"]: THREE.MeshStandardMaterial;
    ["Concrete.004"]: THREE.MeshStandardMaterial;
    ["Color.004"]: THREE.MeshStandardMaterial;
    ["Substation Box.004"]: THREE.MeshStandardMaterial;
    ["Switch Box.004"]: THREE.MeshStandardMaterial;
    ["tank_glass.001"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.001"]: THREE.MeshStandardMaterial;
    ["Water - Pool.001"]: THREE.MeshStandardMaterial;
    ["white.001"]: THREE.MeshStandardMaterial;
    tank_glass: THREE.MeshStandardMaterial;
    ["MF Blue"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]: THREE.MeshStandardMaterial;
    ["white.002"]: THREE.MeshStandardMaterial;
    ["20018 - WYA_PW11_Powdercoat_Monument_Internal Frames.002"]: THREE.MeshStandardMaterial;
    ["- WYA_PC1_Colour_(Precast 150).002"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P11_White Wall Paint.002"]: THREE.MeshStandardMaterial;
    ["MF Blue.001"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P1_White Wall Paint.002"]: THREE.MeshStandardMaterial;
    ["- WYA_PC1_Colour_(Precast 200).002"]: THREE.MeshStandardMaterial;
    ["WYA_Roller Shutter Door.002"]: THREE.MeshStandardMaterial;
    ["WYA_Roller Shutter Door_Mainfreight Blue.002"]: THREE.MeshStandardMaterial;
    ["WYA_Roller Shutter Door Drum_Mainfreight Blue.002"]: THREE.MeshStandardMaterial;
    ["Metal - Paint Finish - Yellow, Matte.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Plasterboard.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P13_Basalt Wall Paint.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P19_Mainfreight White.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Metal Stud.002"]: THREE.MeshStandardMaterial;
    ["Metal-Chrome-Caroma.002"]: THREE.MeshStandardMaterial;
    ["Porcelain-White-Caroma.002"]: THREE.MeshStandardMaterial;
    ["PW11- POWDERCOAT - DULUX MATT BLACK.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P12_DOOR Paint.002"]: THREE.MeshStandardMaterial;
    ["Default.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Plasterboard(Fire Rating).002"]: THREE.MeshStandardMaterial;
    ["- WYA_Plasterboard(Fire Rating)(moisture resistant).002"]: THREE.MeshStandardMaterial;
    ["PW1- POWDERCOAT - DULUX MATT BLACK PG1A9.002"]: THREE.MeshStandardMaterial;
    Glass_Panel: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_WP1_Barestone Internal.002"]: THREE.MeshStandardMaterial;
    ["- WYA_CB1_Zincalume_Trimdek Cladding.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_AL1_Blue Wall Aluminium Cladding.002"]: THREE.MeshStandardMaterial;
    ["- WYA_GL11_Clear glazing.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Visual Indicator Film_FLM11.002"]: THREE.MeshStandardMaterial;
    ["Metal-Steel-Powdercoated-Matte Black_PW11.002"]: THREE.MeshStandardMaterial;
    ["20336 - WYA_Powdercoat_Charcoal_PW1.002"]: THREE.MeshStandardMaterial;
    ["Colorback Glass_GC1.002"]: THREE.MeshStandardMaterial;
    ["Insulation.002"]: THREE.MeshStandardMaterial;
    ["- WYA_CB1_Whitehaven_Kliplok Cladding.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Paint_Colorbond_whitehaven.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Visual Indicator Film_FLM.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_CBX_White Wall Cladding.002"]: THREE.MeshStandardMaterial;
    ["metal.002"]: THREE.MeshStandardMaterial;
    ["RESINA.002"]: THREE.MeshStandardMaterial;
    ["Concrete - Cast In Situ.002"]: THREE.MeshStandardMaterial;
    ["- WYA_Mainfreight_Paint P8_Basalt Door Paint.002"]: THREE.MeshStandardMaterial;
    ["Skylight.002"]: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    ["logo white"]: THREE.MeshStandardMaterial;
    ["MF red"]: THREE.MeshStandardMaterial;
    ["solar panels.025"]: THREE.MeshStandardMaterial;
    wire_153228184: THREE.MeshStandardMaterial;
    ["solar panels"]: THREE.MeshStandardMaterial;
    ["wire_153228184.002"]: THREE.MeshStandardMaterial;
    ["logo.002"]: THREE.MeshStandardMaterial;
    ["wire_153228184.031"]: THREE.MeshStandardMaterial;
    ["BODY_GLOW.002"]: THREE.MeshStandardMaterial;
    ["Plastic.001"]: THREE.MeshStandardMaterial;
    ["Screen.001"]: THREE.MeshStandardMaterial;
    ["Blue.002"]: THREE.MeshStandardMaterial;
    ["Power Box.003"]: THREE.MeshStandardMaterial;
    ["Battery Box"]: THREE.MeshStandardMaterial;
    Concrete: THREE.MeshStandardMaterial;
    Color: THREE.MeshStandardMaterial;
    ["Substation Box"]: THREE.MeshStandardMaterial;
    ["Switch Box"]: THREE.MeshStandardMaterial;
    ["wire_153228184.026"]: THREE.MeshStandardMaterial;
    ["solar panels.026"]: THREE.MeshStandardMaterial;
    ["wire_153228184.027"]: THREE.MeshStandardMaterial;
    ["solar panels.027"]: THREE.MeshStandardMaterial;
    ["wire_153228184.028"]: THREE.MeshStandardMaterial;
    ["solar panels.028"]: THREE.MeshStandardMaterial;
    ["wire_153228184.029"]: THREE.MeshStandardMaterial;
    ["solar panels.029"]: THREE.MeshStandardMaterial;
    ["wire_153228184.030"]: THREE.MeshStandardMaterial;
    ["solar panels.001"]: THREE.MeshStandardMaterial;
    ["wire_153228184.001"]: THREE.MeshStandardMaterial;
    ["solar panels.002"]: THREE.MeshStandardMaterial;
    ["wire_153228184.003"]: THREE.MeshStandardMaterial;
    ["solar panels.003"]: THREE.MeshStandardMaterial;
    ["wire_153228184.004"]: THREE.MeshStandardMaterial;
    ["solar panels.004"]: THREE.MeshStandardMaterial;
    ["wire_153228184.005"]: THREE.MeshStandardMaterial;
    ["solar panels.005"]: THREE.MeshStandardMaterial;
    ["wire_153228184.006"]: THREE.MeshStandardMaterial;
    ["solar panels.006"]: THREE.MeshStandardMaterial;
    ["wire_153228184.007"]: THREE.MeshStandardMaterial;
    ["solar panels.007"]: THREE.MeshStandardMaterial;
    ["wire_153228184.008"]: THREE.MeshStandardMaterial;
    ["solar panels.008"]: THREE.MeshStandardMaterial;
    ["wire_153228184.009"]: THREE.MeshStandardMaterial;
    ["solar panels.009"]: THREE.MeshStandardMaterial;
    ["wire_153228184.010"]: THREE.MeshStandardMaterial;
    ["solar panels.010"]: THREE.MeshStandardMaterial;
    ["wire_153228184.011"]: THREE.MeshStandardMaterial;
    ["solar panels.011"]: THREE.MeshStandardMaterial;
    ["wire_153228184.012"]: THREE.MeshStandardMaterial;
    ["solar panels.012"]: THREE.MeshStandardMaterial;
    ["wire_153228184.013"]: THREE.MeshStandardMaterial;
    ["solar panels.013"]: THREE.MeshStandardMaterial;
    ["wire_153228184.014"]: THREE.MeshStandardMaterial;
    ["solar panels.014"]: THREE.MeshStandardMaterial;
    ["wire_153228184.015"]: THREE.MeshStandardMaterial;
    ["solar panels.015"]: THREE.MeshStandardMaterial;
    ["wire_153228184.016"]: THREE.MeshStandardMaterial;
    ["solar panels.016"]: THREE.MeshStandardMaterial;
    ["wire_153228184.017"]: THREE.MeshStandardMaterial;
    ["solar panels.017"]: THREE.MeshStandardMaterial;
    ["wire_153228184.018"]: THREE.MeshStandardMaterial;
    ["solar panels.018"]: THREE.MeshStandardMaterial;
    ["wire_153228184.019"]: THREE.MeshStandardMaterial;
    ["solar panels.019"]: THREE.MeshStandardMaterial;
    ["wire_153228184.020"]: THREE.MeshStandardMaterial;
    ["solar panels.020"]: THREE.MeshStandardMaterial;
    ["wire_153228184.021"]: THREE.MeshStandardMaterial;
    ["solar panels.021"]: THREE.MeshStandardMaterial;
    ["wire_153228184.022"]: THREE.MeshStandardMaterial;
    ["solar panels.022"]: THREE.MeshStandardMaterial;
    ["wire_153228184.023"]: THREE.MeshStandardMaterial;
    ["solar panels.023"]: THREE.MeshStandardMaterial;
    ["wire_153228184.024"]: THREE.MeshStandardMaterial;
    ["solar panels.024"]: THREE.MeshStandardMaterial;
    ["wire_153228184.025"]: THREE.MeshStandardMaterial;
    ["wire_153228184.033"]: THREE.MeshStandardMaterial;
    ["BODY_GLOW.003"]: THREE.MeshStandardMaterial;
    ["Plastic.002"]: THREE.MeshStandardMaterial;
    ["Screen.002"]: THREE.MeshStandardMaterial;
    ["Blue.003"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/RegencyPark_EmbedTextured_v9.gltf"
  ) as GLTFResult;

  const { scene } = useThree();

  useEffect(() => {
    scene.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        child.material.side = THREE.FrontSide;
      }
    });
  }, []);
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="battery_hero_1"
          position={[-82.74, -10.34, -49.4]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Battery_3_2001" position={[312, 0, 0]}>
            <group
              name="BATTERY_BOX_instance_6001"
              position={[2001.23, -1566.53, -465.75]}
              rotation={[Math.PI / 2, -0.01, 0]}
              scale={-3.08}
            >
              <mesh
                name="Mesh001"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001.geometry}
                material={materials["Battery Box.001"]}
              />
              <mesh
                name="Mesh001_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_1.geometry}
                material={materials["Power Box.004"]}
              />
              <mesh
                name="Mesh001_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_2.geometry}
                material={materials["Battery Box.007"]}
              />
              <mesh
                name="Mesh001_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_3.geometry}
                material={materials["Concrete.001"]}
              />
              <mesh
                name="Mesh001_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_4.geometry}
                material={materials["Color.001"]}
              />
              <mesh
                name="Mesh001_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_5.geometry}
                material={materials["Substation Box.001"]}
              />
              <mesh
                name="Mesh001_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_6.geometry}
                material={materials["Switch Box.001"]}
              />
            </group>
          </group>
        </group>
        <group
          name="battery_hero_2"
          position={[-82.74, -10.34, -55.51]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Battery_3_2003" position={[312, 0, 0]}>
            <group
              name="BATTERY_BOX_instance_6003"
              position={[2001.23, -1566.53, -465.75]}
              rotation={[Math.PI / 2, -0.01, 0]}
              scale={-3.08}
            >
              <mesh
                name="Mesh003"
                castShadow
                receiveShadow
                geometry={nodes.Mesh003.geometry}
                material={materials["Battery Box.008"]}
              />
              <mesh
                name="Mesh003_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh003_1.geometry}
                material={materials["Power Box.005"]}
              />
              <mesh
                name="Mesh003_2"
                castShadow
                receiveShadow
                geometry={nodes.Mesh003_2.geometry}
                material={materials["Battery Box.009"]}
              />
              <mesh
                name="Mesh003_3"
                castShadow
                receiveShadow
                geometry={nodes.Mesh003_3.geometry}
                material={materials["Concrete.004"]}
              />
              <mesh
                name="Mesh003_4"
                castShadow
                receiveShadow
                geometry={nodes.Mesh003_4.geometry}
                material={materials["Color.004"]}
              />
              <mesh
                name="Mesh003_5"
                castShadow
                receiveShadow
                geometry={nodes.Mesh003_5.geometry}
                material={materials["Substation Box.004"]}
              />
              <mesh
                name="Mesh003_6"
                castShadow
                receiveShadow
                geometry={nodes.Mesh003_6.geometry}
                material={materials["Switch Box.004"]}
              />
            </group>
          </group>
        </group>
        <group
          name="water_tank_hero_1"
          position={[-67.38, -10.41, 89.05]}
          rotation={[Math.PI / 2, 0, 3.12]}
          scale={0.01}
        >
          <mesh
            name="tank_4001"
            castShadow
            receiveShadow
            geometry={nodes.tank_4001.geometry}
            material={materials["tank_glass.001"]}
            position={[-77.73, -273.1, -768.14]}
          />
          <mesh
            name="floor_4001"
            castShadow
            receiveShadow
            geometry={nodes.floor_4001.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.001"]
            }
            position={[-77.73, -273.1, -29.82]}
          />
          <mesh
            name="pipes_4001"
            castShadow
            receiveShadow
            geometry={nodes.pipes_4001.geometry}
            material={nodes.pipes_4001.material}
            position={[164.09, 576.54, 8.95]}
          />
          <mesh
            name="roof_4001"
            castShadow
            receiveShadow
            geometry={nodes.roof_4001.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.001"]
            }
            position={[-77.73, -273.1, -1448.3]}
          />
          <mesh
            name="75_water_4001"
            castShadow
            receiveShadow
            geometry={nodes["75_water_4001"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.75]}
          />
          <mesh
            name="ladder_4001"
            castShadow
            receiveShadow
            geometry={nodes.ladder_4001.geometry}
            material={materials["white.001"]}
            position={[164.09, 576.54, -24.05]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </group>
        <group
          name="water_tank_real_1"
          position={[-69.13, -10.41, 98.03]}
          rotation={[Math.PI / 2, 0, 3.12]}
          scale={0.01}
        >
          <mesh
            name="100_water_3"
            castShadow
            receiveShadow
            geometry={nodes["100_water_3"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
          />
          <mesh
            name="25_water_3"
            castShadow
            receiveShadow
            geometry={nodes["25_water_3"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.25]}
          />
          <mesh
            name="75_water_3"
            castShadow
            receiveShadow
            geometry={nodes["75_water_3"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.75]}
          />
          <mesh
            name="50_water_3"
            castShadow
            receiveShadow
            geometry={nodes["50_water_3"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.5]}
          />
          <mesh
            name="tank_3"
            castShadow
            receiveShadow
            geometry={nodes.tank_3.geometry}
            material={materials.tank_glass}
            position={[-77.73, -273.1, -768.14]}
          />
          <group name="roof_3" position={[-77.73, -273.1, -1448.3]}>
            <mesh
              name="Mesh059"
              castShadow
              receiveShadow
              geometry={nodes.Mesh059.geometry}
              material={materials["MF Blue"]}
            />
            <mesh
              name="Mesh059_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh059_1.geometry}
              material={
                materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]
              }
            />
            <mesh
              name="Mesh059_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh059_2.geometry}
              material={materials["white.002"]}
            />
          </group>
        </group>
        <group
          name="water_tank_real_2"
          position={[-78.62, -10.41, 89.05]}
          rotation={[Math.PI / 2, 0, 3.12]}
          scale={0.01}
        >
          <mesh
            name="pipes_4"
            castShadow
            receiveShadow
            geometry={nodes.pipes_4.geometry}
            material={nodes.pipes_4.material}
            position={[164.09, 576.54, 8.95]}
          />
          <mesh
            name="roof_4"
            castShadow
            receiveShadow
            geometry={nodes.roof_4.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]
            }
            position={[-77.73, -273.1, -1448.3]}
          />
          <mesh
            name="tank_4"
            castShadow
            receiveShadow
            geometry={nodes.tank_4.geometry}
            material={materials.tank_glass}
            position={[-77.73, -273.1, -768.14]}
          />
          <mesh
            name="100_water_4"
            castShadow
            receiveShadow
            geometry={nodes["100_water_4"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
          />
          <mesh
            name="25_water_4"
            castShadow
            receiveShadow
            geometry={nodes["25_water_4"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.25]}
          />
          <mesh
            name="50_water_4"
            castShadow
            receiveShadow
            geometry={nodes["50_water_4"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.5]}
          />
          <mesh
            name="75_water_4"
            castShadow
            receiveShadow
            geometry={nodes["75_water_4"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.75]}
          />
          <mesh
            name="floor_4"
            castShadow
            receiveShadow
            geometry={nodes.floor_4.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]
            }
            position={[-77.73, -273.1, -29.82]}
          />
          <mesh
            name="ladder_4"
            castShadow
            receiveShadow
            geometry={nodes.ladder_4.geometry}
            material={materials["white.002"]}
            position={[164.09, 576.54, -24.05]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </group>
        <group
          name="water_tank_real_4"
          position={[-78.94, -10.41, -69.22]}
          rotation={[Math.PI / 2, 0, 3.12]}
          scale={0.01}
        >
          <mesh
            name="100_water_2"
            castShadow
            receiveShadow
            geometry={nodes["100_water_2"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
          />
          <mesh
            name="50_water_2"
            castShadow
            receiveShadow
            geometry={nodes["50_water_2"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.5]}
          />
          <mesh
            name="floor_2"
            castShadow
            receiveShadow
            geometry={nodes.floor_2.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]
            }
            position={[-77.73, -273.1, -29.82]}
          />
          <mesh
            name="pipes_2"
            castShadow
            receiveShadow
            geometry={nodes.pipes_2.geometry}
            material={nodes.pipes_2.material}
            position={[164.09, 576.54, 8.95]}
          />
          <mesh
            name="roof_2"
            castShadow
            receiveShadow
            geometry={nodes.roof_2.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]
            }
            position={[-77.73, -273.1, -1448.3]}
          />
          <mesh
            name="tank_2"
            castShadow
            receiveShadow
            geometry={nodes.tank_2.geometry}
            material={materials.tank_glass}
            position={[-77.73, -273.1, -768.14]}
          />
          <mesh
            name="25_water_2"
            castShadow
            receiveShadow
            geometry={nodes["25_water_2"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.25]}
          />
          <mesh
            name="75_water_2"
            castShadow
            receiveShadow
            geometry={nodes["75_water_2"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.75]}
          />
          <mesh
            name="ladder_2"
            castShadow
            receiveShadow
            geometry={nodes.ladder_2.geometry}
            material={materials["white.002"]}
            position={[164.09, 576.54, -24.05]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </group>
        <group
          name="water_tank_real_3"
          position={[-69.45, -10.41, -75.47]}
          rotation={[Math.PI / 2, 0, 3.12]}
          scale={0.01}
        >
          <mesh
            name="100_water"
            castShadow
            receiveShadow
            geometry={nodes["100_water"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
          />
          <mesh
            name="50_water"
            castShadow
            receiveShadow
            geometry={nodes["50_water"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.5]}
          />
          <mesh
            name="floor"
            castShadow
            receiveShadow
            geometry={nodes.floor.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]
            }
            position={[-77.73, -273.1, -29.82]}
          />
          <mesh
            name="pipes"
            castShadow
            receiveShadow
            geometry={nodes.pipes.geometry}
            material={nodes.pipes.material}
            position={[164.09, 576.55, 8.95]}
          />
          <mesh
            name="roof"
            castShadow
            receiveShadow
            geometry={nodes.roof.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P2_WALL BLUE Paint.002"]
            }
            position={[-77.73, -273.1, -1448.3]}
          />
          <mesh
            name="tank"
            castShadow
            receiveShadow
            geometry={nodes.tank.geometry}
            material={materials.tank_glass}
            position={[-77.73, -273.1, -768.14]}
          />
          <mesh
            name="25_water"
            castShadow
            receiveShadow
            geometry={nodes["25_water"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.25]}
          />
          <mesh
            name="75_water"
            castShadow
            receiveShadow
            geometry={nodes["75_water"].geometry}
            material={materials["Water - Pool.001"]}
            position={[-77.73, -273.1, -73.72]}
            scale={[1, 1, 0.75]}
          />
          <mesh
            name="ladder"
            castShadow
            receiveShadow
            geometry={nodes.ladder.geometry}
            material={materials["white.002"]}
            position={[164.09, 576.55, -24.05]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </group>
        <group
          name="battery_real_2"
          position={[-59.17, -10.34, -43.21]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Battery_0_2">
            <mesh
              name="BATTERY_BOX_2"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX_2.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
          <group name="Battery_1_2" position={[104, 0, 0]}>
            <mesh
              name="BATTERY_BOX_instance_4"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX_instance_4.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
          <group name="Battery_2_2" position={[208, 0, 0]}>
            <mesh
              name="BATTERY_BOX_instance_5"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX_instance_5.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
          <group name="Battery_3_2" position={[312, 0, 0]}>
            <mesh
              name="BATTERY_BOX_instance_6"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX_instance_6.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
        </group>
        <group
          name="batteries_2"
          position={[-56.06, -10.34, -40.23]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.01}
        >
          <group name="Battery_0">
            <mesh
              name="BATTERY_BOX"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
          <group name="Battery_1" position={[104, 0, 0]}>
            <mesh
              name="BATTERY_BOX_instance"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX_instance.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
          <group name="Battery_2" position={[208, 0, 0]}>
            <mesh
              name="BATTERY_BOX_instance_2"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX_instance_2.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
          <group name="Battery_3" position={[312, 0, 0]}>
            <mesh
              name="BATTERY_BOX_instance_3"
              castShadow
              receiveShadow
              geometry={nodes.BATTERY_BOX_instance_3.geometry}
              material={materials["Battery Box.009"]}
              position={[0, 153.39, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={-1}
            />
          </group>
        </group>
        <group name="Warehouse" rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh
            name="Mesh076"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076.geometry}
            material={
              materials[
                "20018 - WYA_PW11_Powdercoat_Monument_Internal Frames.002"
              ]
            }
          />
          <mesh
            name="Mesh076_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_1.geometry}
            material={materials["- WYA_PC1_Colour_(Precast 150).002"]}
          />
          <mesh
            name="Mesh076_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_2.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P11_White Wall Paint.002"]
            }
          />
          <mesh
            name="Mesh076_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_3.geometry}
            material={materials["MF Blue.001"]}
          />
          <mesh
            name="Mesh076_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_4.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P1_White Wall Paint.002"]
            }
          />
          <mesh
            name="Mesh076_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_5.geometry}
            material={materials["- WYA_PC1_Colour_(Precast 200).002"]}
          />
          <mesh
            name="Mesh076_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_6.geometry}
            material={materials["WYA_Roller Shutter Door.002"]}
          />
          <mesh
            name="Mesh076_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_7.geometry}
            material={materials["WYA_Roller Shutter Door_Mainfreight Blue.002"]}
          />
          <mesh
            name="Mesh076_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_8.geometry}
            material={
              materials["WYA_Roller Shutter Door Drum_Mainfreight Blue.002"]
            }
          />
          <mesh
            name="Mesh076_9"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_9.geometry}
            material={materials["Metal - Paint Finish - Yellow, Matte.002"]}
          />
          <mesh
            name="Mesh076_10"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_10.geometry}
            material={materials["- WYA_Plasterboard.002"]}
          />
          <mesh
            name="Mesh076_11"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_11.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P13_Basalt Wall Paint.002"]
            }
          />
          <mesh
            name="Mesh076_12"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_12.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P19_Mainfreight White.002"]
            }
          />
          <mesh
            name="Mesh076_13"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_13.geometry}
            material={materials["- WYA_Metal Stud.002"]}
          />
          <mesh
            name="Mesh076_14"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_14.geometry}
            material={materials["Metal-Chrome-Caroma.002"]}
          />
          <mesh
            name="Mesh076_15"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_15.geometry}
            material={materials["Porcelain-White-Caroma.002"]}
          />
          <mesh
            name="Mesh076_16"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_16.geometry}
            material={materials["PW11- POWDERCOAT - DULUX MATT BLACK.002"]}
          />
          <mesh
            name="Mesh076_17"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_17.geometry}
            material={materials["- WYA_Mainfreight_Paint P12_DOOR Paint.002"]}
          />
          <mesh
            name="Mesh076_18"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_18.geometry}
            material={materials["Default.002"]}
          />
          <mesh
            name="Mesh076_19"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_19.geometry}
            material={materials["- WYA_Plasterboard(Fire Rating).002"]}
          />
          <mesh
            name="Mesh076_20"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_20.geometry}
            material={
              materials[
                "- WYA_Plasterboard(Fire Rating)(moisture resistant).002"
              ]
            }
          />
          <mesh
            name="Mesh076_21"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_21.geometry}
            material={materials["PW1- POWDERCOAT - DULUX MATT BLACK PG1A9.002"]}
          />
          <mesh
            name="Mesh076_22"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_22.geometry}
            material={materials.Glass_Panel}
          />
          <mesh
            name="Mesh076_23"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_23.geometry}
            material={materials["- WYA_Mainfreight_WP1_Barestone Internal.002"]}
          />
          <mesh
            name="Mesh076_24"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_24.geometry}
            material={materials["- WYA_CB1_Zincalume_Trimdek Cladding.002"]}
          />
          <mesh
            name="Mesh076_25"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_25.geometry}
            material={
              materials[
                "- WYA_Mainfreight_AL1_Blue Wall Aluminium Cladding.002"
              ]
            }
          />
          <mesh
            name="Mesh076_26"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_26.geometry}
            material={materials["- WYA_GL11_Clear glazing.002"]}
          />
          <mesh
            name="Mesh076_27"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_27.geometry}
            material={materials["- WYA_Visual Indicator Film_FLM11.002"]}
          />
          <mesh
            name="Mesh076_28"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_28.geometry}
            material={
              materials["Metal-Steel-Powdercoated-Matte Black_PW11.002"]
            }
          />
          <mesh
            name="Mesh076_29"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_29.geometry}
            material={materials["20336 - WYA_Powdercoat_Charcoal_PW1.002"]}
          />
          <mesh
            name="Mesh076_30"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_30.geometry}
            material={materials["Colorback Glass_GC1.002"]}
          />
          <mesh
            name="Mesh076_31"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_31.geometry}
            material={materials["Insulation.002"]}
          />
          <mesh
            name="Mesh076_32"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_32.geometry}
            material={materials["- WYA_CB1_Whitehaven_Kliplok Cladding.002"]}
          />
          <mesh
            name="Mesh076_33"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_33.geometry}
            material={materials["- WYA_Paint_Colorbond_whitehaven.002"]}
          />
          <mesh
            name="Mesh076_34"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_34.geometry}
            material={materials["- WYA_Visual Indicator Film_FLM.002"]}
          />
          <mesh
            name="Mesh076_35"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_35.geometry}
            material={
              materials["- WYA_Mainfreight_CBX_White Wall Cladding.002"]
            }
          />
          <mesh
            name="Mesh076_36"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_36.geometry}
            material={materials["metal.002"]}
          />
          <mesh
            name="Mesh076_37"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_37.geometry}
            material={materials["RESINA.002"]}
          />
          <mesh
            name="Mesh076_38"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_38.geometry}
            material={materials["Concrete - Cast In Situ.002"]}
          />
          <mesh
            name="Mesh076_39"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_39.geometry}
            material={
              materials["- WYA_Mainfreight_Paint P8_Basalt Door Paint.002"]
            }
          />
          <mesh
            name="Mesh076_40"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_40.geometry}
            material={materials["Skylight.002"]}
          />
          <mesh
            name="Mesh076_41"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_41.geometry}
            material={materials.metal}
          />
          <mesh
            name="Mesh076_42"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_42.geometry}
            material={materials.metal}
          />
          <mesh
            name="Mesh076_43"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_43.geometry}
            material={materials["logo white"]}
          />
          <mesh
            name="Mesh076_44"
            castShadow
            receiveShadow
            geometry={nodes.Mesh076_44.geometry}
            material={materials["MF red"]}
          />
        </group>
        <group
          name="solar_hero_1"
          position={[23.33, 4.37, -41.58]}
          rotation={[2.49, 0, -Math.PI / 2]}
          scale={0.1}
        >
          <mesh
            name="Mesh087"
            castShadow
            receiveShadow
            geometry={nodes.Mesh087.geometry}
            material={materials["solar panels.025"]}
          />
          <mesh
            name="Mesh087_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh087_1.geometry}
            material={materials.wire_153228184}
          />
        </group>
        <group
          name="solar_real_2"
          position={[24.62, 4.43, 21.64]}
          rotation={[1.61, 1.54, 0]}
          scale={0.02}
        >
          <mesh
            name="Mesh033"
            castShadow
            receiveShadow
            geometry={nodes.Mesh033.geometry}
            material={materials["solar panels"]}
          />
          <mesh
            name="Mesh033_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh033_1.geometry}
            material={materials["wire_153228184.002"]}
          />
        </group>
        <group
          name="generator_hero_1"
          position={[-59.32, -7.46, -58.39]}
          rotation={[Math.PI, -0.01, Math.PI]}
          scale={0.03}
        >
          <mesh
            name="Generator_1"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1.geometry}
            material={materials["logo.002"]}
          />
          <mesh
            name="Generator_1_1"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1_1.geometry}
            material={materials["wire_153228184.031"]}
          />
          <mesh
            name="Generator_1_2"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1_2.geometry}
            material={materials["BODY_GLOW.002"]}
          />
          <mesh
            name="Generator_1_3"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1_3.geometry}
            material={materials["Plastic.001"]}
          />
          <mesh
            name="Generator_1_4"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1_4.geometry}
            material={materials["Screen.001"]}
          />
          <mesh
            name="Generator_1_5"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1_5.geometry}
            material={materials["Blue.002"]}
          />
        </group>
        <group
          name="POWER_BOX_1"
          position={[-61.45, -10.27, -40.8]}
          rotation={[-Math.PI, -1.57, 0]}
          scale={-0.01}
        >
          <mesh
            name="Mesh"
            castShadow
            receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials["Power Box.003"]}
          />
          <mesh
            name="Mesh_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials["Battery Box"]}
          />
          <mesh
            name="Mesh_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_2.geometry}
            material={materials.Concrete}
          />
          <mesh
            name="Mesh_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3.geometry}
            material={materials.Color}
          />
          <mesh
            name="Mesh_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_4.geometry}
            material={materials["Substation Box"]}
          />
          <mesh
            name="Mesh_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_5.geometry}
            material={materials["Switch Box"]}
          />
        </group>
        <group
          name="solar_real_1"
          position={[49.96, 3.15, -14.57]}
          rotation={[1.53, 1.54, 0]}
          scale={0.02}
        >
          <mesh
            name="Mesh081"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081.geometry}
            material={materials["solar panels.025"]}
          />
          <mesh
            name="Mesh081_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_1.geometry}
            material={materials["wire_153228184.026"]}
          />
          <mesh
            name="Mesh081_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_2.geometry}
            material={materials["solar panels.026"]}
          />
          <mesh
            name="Mesh081_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_3.geometry}
            material={materials["wire_153228184.027"]}
          />
          <mesh
            name="Mesh081_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_4.geometry}
            material={materials["solar panels.027"]}
          />
          <mesh
            name="Mesh081_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_5.geometry}
            material={materials["wire_153228184.028"]}
          />
          <mesh
            name="Mesh081_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_6.geometry}
            material={materials["solar panels.028"]}
          />
          <mesh
            name="Mesh081_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_7.geometry}
            material={materials["wire_153228184.029"]}
          />
          <mesh
            name="Mesh081_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_8.geometry}
            material={materials["solar panels.029"]}
          />
          <mesh
            name="Mesh081_9"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_9.geometry}
            material={materials["wire_153228184.030"]}
          />
          <mesh
            name="Mesh081_10"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_10.geometry}
            material={materials["solar panels.001"]}
          />
          <mesh
            name="Mesh081_11"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_11.geometry}
            material={materials["wire_153228184.001"]}
          />
          <mesh
            name="Mesh081_12"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_12.geometry}
            material={materials["solar panels.002"]}
          />
          <mesh
            name="Mesh081_13"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_13.geometry}
            material={materials["wire_153228184.003"]}
          />
          <mesh
            name="Mesh081_14"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_14.geometry}
            material={materials["solar panels"]}
          />
          <mesh
            name="Mesh081_15"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_15.geometry}
            material={materials["wire_153228184.002"]}
          />
          <mesh
            name="Mesh081_16"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_16.geometry}
            material={materials["solar panels.003"]}
          />
          <mesh
            name="Mesh081_17"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_17.geometry}
            material={materials["wire_153228184.004"]}
          />
          <mesh
            name="Mesh081_18"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_18.geometry}
            material={materials["solar panels.004"]}
          />
          <mesh
            name="Mesh081_19"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_19.geometry}
            material={materials["wire_153228184.005"]}
          />
          <mesh
            name="Mesh081_20"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_20.geometry}
            material={materials["solar panels.005"]}
          />
          <mesh
            name="Mesh081_21"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_21.geometry}
            material={materials["wire_153228184.006"]}
          />
          <mesh
            name="Mesh081_22"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_22.geometry}
            material={materials["solar panels.006"]}
          />
          <mesh
            name="Mesh081_23"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_23.geometry}
            material={materials["wire_153228184.007"]}
          />
          <mesh
            name="Mesh081_24"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_24.geometry}
            material={materials["solar panels.007"]}
          />
          <mesh
            name="Mesh081_25"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_25.geometry}
            material={materials["wire_153228184.008"]}
          />
          <mesh
            name="Mesh081_26"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_26.geometry}
            material={materials["solar panels.008"]}
          />
          <mesh
            name="Mesh081_27"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_27.geometry}
            material={materials["wire_153228184.009"]}
          />
          <mesh
            name="Mesh081_28"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_28.geometry}
            material={materials["solar panels.009"]}
          />
          <mesh
            name="Mesh081_29"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_29.geometry}
            material={materials["wire_153228184.010"]}
          />
          <mesh
            name="Mesh081_30"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_30.geometry}
            material={materials["solar panels.010"]}
          />
          <mesh
            name="Mesh081_31"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_31.geometry}
            material={materials["wire_153228184.011"]}
          />
          <mesh
            name="Mesh081_32"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_32.geometry}
            material={materials["solar panels.011"]}
          />
          <mesh
            name="Mesh081_33"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_33.geometry}
            material={materials["wire_153228184.012"]}
          />
          <mesh
            name="Mesh081_34"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_34.geometry}
            material={materials["solar panels.012"]}
          />
          <mesh
            name="Mesh081_35"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_35.geometry}
            material={materials["wire_153228184.013"]}
          />
          <mesh
            name="Mesh081_36"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_36.geometry}
            material={materials["solar panels.013"]}
          />
          <mesh
            name="Mesh081_37"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_37.geometry}
            material={materials["wire_153228184.014"]}
          />
          <mesh
            name="Mesh081_38"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_38.geometry}
            material={materials["solar panels.014"]}
          />
          <mesh
            name="Mesh081_39"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_39.geometry}
            material={materials["wire_153228184.015"]}
          />
          <mesh
            name="Mesh081_40"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_40.geometry}
            material={materials["solar panels.015"]}
          />
          <mesh
            name="Mesh081_41"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_41.geometry}
            material={materials["wire_153228184.016"]}
          />
          <mesh
            name="Mesh081_42"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_42.geometry}
            material={materials["solar panels.016"]}
          />
          <mesh
            name="Mesh081_43"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_43.geometry}
            material={materials["wire_153228184.017"]}
          />
          <mesh
            name="Mesh081_44"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_44.geometry}
            material={materials["solar panels.017"]}
          />
          <mesh
            name="Mesh081_45"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_45.geometry}
            material={materials["wire_153228184.018"]}
          />
          <mesh
            name="Mesh081_46"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_46.geometry}
            material={materials["solar panels.018"]}
          />
          <mesh
            name="Mesh081_47"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_47.geometry}
            material={materials["wire_153228184.019"]}
          />
          <mesh
            name="Mesh081_48"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_48.geometry}
            material={materials["solar panels.019"]}
          />
          <mesh
            name="Mesh081_49"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_49.geometry}
            material={materials["wire_153228184.020"]}
          />
          <mesh
            name="Mesh081_50"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_50.geometry}
            material={materials["solar panels.020"]}
          />
          <mesh
            name="Mesh081_51"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_51.geometry}
            material={materials["wire_153228184.021"]}
          />
          <mesh
            name="Mesh081_52"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_52.geometry}
            material={materials["solar panels.021"]}
          />
          <mesh
            name="Mesh081_53"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_53.geometry}
            material={materials["wire_153228184.022"]}
          />
          <mesh
            name="Mesh081_54"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_54.geometry}
            material={materials["solar panels.022"]}
          />
          <mesh
            name="Mesh081_55"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_55.geometry}
            material={materials["wire_153228184.023"]}
          />
          <mesh
            name="Mesh081_56"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_56.geometry}
            material={materials["solar panels.023"]}
          />
          <mesh
            name="Mesh081_57"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_57.geometry}
            material={materials["wire_153228184.024"]}
          />
          <mesh
            name="Mesh081_58"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_58.geometry}
            material={materials["solar panels.024"]}
          />
          <mesh
            name="Mesh081_59"
            castShadow
            receiveShadow
            geometry={nodes.Mesh081_59.geometry}
            material={materials["wire_153228184.025"]}
          />
        </group>
        <group
          name="power_box_real_2"
          position={[-61.45, -10.27, -43.87]}
          rotation={[-Math.PI, -1.57, 0]}
          scale={-0.01}
        >
          <mesh
            name="Mesh002"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002.geometry}
            material={materials["Power Box.003"]}
          />
          <mesh
            name="Mesh002_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_1.geometry}
            material={materials["Battery Box"]}
          />
          <mesh
            name="Mesh002_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_2.geometry}
            material={materials.Concrete}
          />
          <mesh
            name="Mesh002_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_3.geometry}
            material={materials.Color}
          />
          <mesh
            name="Mesh002_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_4.geometry}
            material={materials["Substation Box"]}
          />
          <mesh
            name="Mesh002_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_5.geometry}
            material={materials["Switch Box"]}
          />
        </group>
        <group
          name="generator_real_1"
          position={[-100.22, -9.45, -77.9]}
          rotation={[Math.PI, -0.06, Math.PI]}
          scale={0.01}
        >
          <mesh
            name="Generator_1001"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1001.geometry}
            material={materials["logo.002"]}
          />
          <mesh
            name="Generator_1001_1"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1001_1.geometry}
            material={materials["wire_153228184.033"]}
          />
          <mesh
            name="Generator_1001_2"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1001_2.geometry}
            material={materials["BODY_GLOW.003"]}
          />
          <mesh
            name="Generator_1001_3"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1001_3.geometry}
            material={materials["Plastic.002"]}
          />
          <mesh
            name="Generator_1001_4"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1001_4.geometry}
            material={materials["Screen.002"]}
          />
          <mesh
            name="Generator_1001_5"
            castShadow
            receiveShadow
            geometry={nodes.Generator_1001_5.geometry}
            material={materials["Blue.003"]}
          />
        </group>
      </group>
    </group>
  );
}

export default Model;

useGLTF.preload("/RegencyPark_EmbedTextured_v9.gltf");
